### ISSUE TITLE
[swc-angular-plugin] Issue with inherited classes

### ISSUE THREAD

**Issue by santiagof4** [jscutlery/devkit#376]
Hello!

First of all, thanks a lot for the effort! This plugin has already incredible results in our huge project with more than 2000 tests.

## The issue
When running our tests with plain Jest, everything works (but super slow 😉), but when running our tests with swc-angular this issue arises:

Looks like classes that extend from other class lose values of those properties that are not present in the parent class.

### Example:
```
interface IModelBase {
  id?: string;
  name: string;
}

class ModelBase implements IModelBase {
  id?: string;
  name: string;

  constructor(model: Partial<IModelBase>) {
    Object.assign(this, model);
  }
}

interface IModel {
  version: number;
}

export class Model extends ModelBase implements IModel {
  version: number;

  constructor(model: Partial<IModel & IModelBase>) {
    super(model);
  }
}
```

When testing something with that class, `version` is always undefined:

```
import { Model } from './model';

describe("failing class tests", () => {
  it('should init class with all the values', () => {
    const model = new Model({ id: '123', name: 'test', version: 1 });

    expect(model.id).toEqual('123');
    expect(model.name).toEqual('test');
    expect(model.version).toEqual(1); // This fails, 'version' is undefined
  })
})
```

This also works with Jasmine and in normal runtime.

## Reproduction
https://github.com/santiagof4/jest-angular-swc-class-reproduction

1. clone package
2. `npm install`
3. `nx test`
4. Test in https://github.com/santiagof4/jest-angular-swc-class-reproduction/blob/main/src/app/failing-test.spec.ts fails.

**Comment by pumano** [comment]
code above transpiled to:

```ts
class ModelBase {
    constructor(model) {
        Object.assign(this, model);
    }
}
export class Model extends ModelBase {
    constructor(model) {
        super(model);
    }
}
```
see [swc playground](https://play.swc.rs/?version=1.9.3&code=H4sIAAAAAAAAA5WPQQrCMBBF9z3FrKQF8QBVFNy5EL1Cmo51JJmUZCoF6d1Ng1IREV3%2BwHuTRyzoT0oj7PauRrNVAeGWAVC9KSGIJ26WcbKyOO0hy7RRIcDEkG0NWmQJf5nig3YcV6fF%2BdyOZAlH5YWUWU2mdZFcAIfqgloW8Tg1nMuZwhwSVYzyYfwavTUl8oo%2BkOMSuLMV%2BtSAfeu8wEsKYC%2FI9dewz7pfQmAGH4pC1%2BIDeDbcAWlmemiWAQAA&config=H4sIAAAAAAAAA3VQyw6CQAy8%2BxWkZw%2BGgwevGm58RLMUsmYfpC2JxPjvLrAgxnhrO9POTJ%2BHooC7GLgUz1SmpkcW4q1PExmD4iNNQMeexLDtFY4rqjJBLTqhbdaQiYwaWRKkPGTklQmgjEHayH4vMwjdqLWBqshXhyKVJdfI%2F%2BM1KTao%2BKWRCI46NONtpWV47wAUuSOdIpGUp7LMccDFKPStCN4G2457pyb6nkl%2BrXkMndv2F8VDVgUfm2EG86OnZy4OzvAhrWLbYbBSr5tzjtcbudbkRrQBAAA%3D)

when reproduce transpiled code and use it with test:

```ts
describe("failing class tests", () => {
  it('should init class with all the values', () => {
    const model = new Model({ id: '123', name: 'test', version: 1 });

    expect(model.id).toEqual('123');
    expect(model.name).toEqual('test');
    expect(model.version).toEqual(1); // This fails, 'version' is undefined
  })
})
```
it works as expected, but when use with classes and interfaces, it not working any more and fails on "version": 1

Try to dig to it soon

**Comment by edbzn** [comment]
We've updated @swc/core and its dependencies so it is probably fixed in [swc-angular-0.19.0](https://github.com/jscutlery/devkit/releases/tag/swc-angular-0.19.0), could you validate it @santiagof4?

**Comment by santiagof4** [comment]
> We've updated @swc/core and its dependencies so it is probably fixed in [swc-angular-0.19.0](https://github.com/jscutlery/devkit/releases/tag/swc-angular-0.19.0), could you validate it @santiagof4?

I just test it in the minimal reproduction repo posted in this issue and the error still occurs. Same test fails. 😢

**Comment by yharaskrik** [comment]
I am also seeing certain tests fail when inheritance is being used (we are trying to phase it out but aren't quite there)

**Comment by atomicrobokid** [comment]
Also seeing this issue when tests are importing a module that has inherited classes implemented in some of the components

**Comment by atomicrobokid** [comment]
@edbzn - i don't suppose you've had a chance to look at this issue again? We have a fair number of abstract classes in our app that are implemented by other components that all fail with this plugin. Would be great if it was fixed so we can move to swc 🙏

**Comment by ryan-bendel** [comment]
Got this working @edbzn @atomicrobokid 

I'll have to take a fork for the time being as this might not work for everyone, i'll let you think of an ideal implementation:

I modified your `swcAngularPreset` function in `node_modules` to test it:

```typescript
transform: {
  legacyDecorator: true,
  decoratorMetadata: true,
  useDefineForClassFields: true
},
target: 'ES2022',
```

`useDefineForClassFields: true` and `target: 'ES2022'` being the key. Worked perfectly after that. 100+libs and over 80,000 tests later, happy days.

**Comment by yjaaidi** [comment]
Hey! Sorry for the delay. I had the fix ready and my son was born that same day! So I got somewhat interrupted 😅... but now, I'm back 😊

I've added the `useDefineForClassFields` option to `swcAngularPreset` to let users control it.

Users in the situation of @santiagof4 (inherited properties) must either 
- update their code and use `declare` (i.e. `declare version: number` in the child class)
- or turn off `useDefineForClassFields` (i.e. `swcAngularPreset({useDefineForClassFields: false})`

Thank you all for your patience and for contributing with solutions. By the way, @ryan-bendel , did you mean `useDefineForClassFields: false`? or did you have a different problem?

**Comment by yjaaidi** [comment]
By the way, I've also added a command to debug the transform on any file:

```sh
nx debug swc-angular-debug tests/playwright-ct-angular-demo/src/recipe-search.component.ts
```

**Comment by ryan-bendel** [comment]
@yjaaidi congratulations! :) 

I've just installed the update, weirdly, i have to set the value to `true` for my tests to pass

My base class looks something like:
```
@Directive()
export abstract class BaseComponent
```

And the component that inherits:
```
export class ChildComponent extends BaseComponent
```

Not clear why that works, i'll have a bit more of a dig into what that does and my tsconfig etc when i get a chance

**Comment by ryan-bendel** [comment]
One last thing @yjaaidi when you get a chance (unrelated sorry), could you bump the @swc/core version to latest? 🙏
